import type { AppsData } from "~/types";

const apps: AppsData[] = [
  {
    id: "launchpad",
    title: "Launchpad",
    desktop: false,
    img: "img/icons/launchpad.png",
  },
  {
    id: "finder",
    title: "Finder",
    desktop: true,
    width: 960,
    height: 590,
    minWidth: 680,
    minHeight: 420,
    x: -40,
    y: -20,
    img: "img/icons/finder.png",
    mobileTitle: "Files",
    mobileImg: "img/icons/folder-generic.png",
    content: <Finder />,
  },
  {
    id: "bear",
    title: "Project Notes",
    desktop: true,
    width: 960,
    height: 590,
    minWidth: 760,
    minHeight: 460,
    hideOnMobile: true,
    x: 30,
    y: 10,
    img: "img/icons/bear.png",
    content: <Bear />,
  },
  {
    id: "typora",
    title: "Resume",
    desktop: true,
    width: 820,
    height: 640,
    minWidth: 560,
    minHeight: 460,
    show: true,
    hideOnMobile: true,
    xPercent: -0.1,
    y: -20,
    img: "img/icons/typora.png",
    content: <Typora />,
  },
  {
    id: "terminal",
    title: "Terminal",
    desktop: true,
    width: 780,
    height: 470,
    minWidth: 560,
    minHeight: 360,
    show: true,
    dockOnMobile: true,
    xPercent: 0.1,
    y: 10,
    img: "img/icons/terminal.png",
    content: <Terminal />,
  },
  {
    id: "vscode",
    title: "VS Code",
    desktop: true,
    width: 920,
    height: 620,
    minWidth: 680,
    minHeight: 440,
    hideOnMobile: true,
    x: 80,
    y: -30,
    img: "img/icons/vscode.png",
    content: <VSCode />,
  },
  {
    id: "safari",
    title: "Browser",
    desktop: true,
    width: 1024,
    minWidth: 420,
    minHeight: 260,
    x: -20,
    img: "img/icons/safari.png",
    dockOnMobile: true,
    content: <Safari />,
  },
  {
    id: "photos",
    title: "Photos",
    desktop: true,
    width: 820,
    height: 540,
    minWidth: 620,
    minHeight: 420,
    x: 40,
    y: -20,
    img: "img/icons/photos.png",
    content: <Photos />,
  },
  {
    id: "mail",
    title: "Contact",
    desktop: true,
    width: 860,
    height: 540,
    minWidth: 640,
    minHeight: 400,
    x: 20,
    y: -10,
    img: "img/icons/mail.png",
    content: <Mail />,
  },
  {
    id: "notes",
    title: "Notes",
    desktop: true,
    width: 720,
    height: 480,
    minWidth: 480,
    minHeight: 340,
    x: 30,
    y: -10,
    img: "img/icons/notes.png",
    content: <Notes />,
  },
  {
    id: "system-settings",
    title: "Settings",
    desktop: true,
    width: 720,
    height: 520,
    minWidth: 580,
    minHeight: 420,
    x: -40,
    y: 10,
    img: "img/icons/settings.png",
    mobileTitle: "Settings",
    content: <SystemSettings />,
  },
  {
    id: "github",
    title: "GitHub",
    desktop: false,
    hideOnMobile: true,
    img: "img/icons/github.png",
    link: "https://github.com/leviance",
  },
  {
    id: "linkedin",
    title: "LinkedIn",
    desktop: false,
    hideOnMobile: true,
    img: "img/icons/sf-icons/contacts.svg",
    link: "https://www.linkedin.com/in/d%C5%A9ng-d%C6%B0%C6%A1ng-95578a208/",
  },
  {
    id: "calculator",
    title: "Calculator",
    desktop: true,
    width: 280,
    height: 420,
    x: 40,
    y: 20,
    img: "img/icons/calculator.png",
    content: <Calculator />,
    hideFromDock: true,
  },
  {
    id: "app-store",
    title: "Project Store",
    desktop: true,
    width: 760,
    height: 540,
    minWidth: 580,
    minHeight: 420,
    x: -30,
    y: 20,
    img: "img/icons/app-store.png",
    content: <AppStore />,
    hideFromDock: true,
  },
  {
    id: "siri",
    title: "Assistant",
    desktop: true,
    width: 860,
    height: 500,
    show: false,
    hideOnMobile: true,
    y: -40,
    img: "img/icons/siri.png",
    content: <Siri />,
    hideFromDock: true,
  },
  {
    id: "messages",
    title: "Messages",
    desktop: true,
    width: 740,
    height: 500,
    minWidth: 560,
    minHeight: 380,
    x: -50,
    y: 10,
    img: "img/icons/messages.png",
    content: <Messages />,
    hideFromDock: true,
  },
  {
    id: "music",
    title: "Music",
    desktop: true,
    width: 780,
    height: 500,
    minWidth: 580,
    minHeight: 380,
    x: -30,
    y: 20,
    img: "img/icons/music.png",
    content: <Music />,
    hideFromDock: true,
  },
];

export default apps;
